apiVersion: v1
kind: Service
metadata:
  name: servicepatrol
  namespace: servicepatrol
spec:
  type: NodePort
  selector:
    app: servicepatrol
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30096
